### ISSUE TITLE
STK Mallet broken and Carla icons missing

### ISSUE THREAD

**Issue by Jacalz** [flathub/io.lmms.LMMS#4] opened 2019-06-27 17:34 UTC
Below is a list of issues with the LMMS flatpak that should be adressed:

- [x]  Carla Rack and Carla Patchbay show no icons in instrument plugins menu along with no icons at all in the Song-Editor.
![image](https://user-images.githubusercontent.com/25466657/60287376-ff67d780-9911-11e9-8ec3-8c663ea7a5eb.png)

- [ ] Mallets doesn't work due to stk not being correctly configured. It doesn't find the files in the rawwave folder, they are used to produce the sounds, and thus we get none.
![image](https://user-images.githubusercontent.com/25466657/60287509-5bcaf700-9912-11e9-9be1-c95ac37ced94.png)

**Comment by hfiguiere** [comment] 2019-07-05 17:19
For Mallets, I'm not sure what's happening, but it works here with the flatpak.

**Comment by hfiguiere** [comment] 2020-05-20 01:24
This should be fixed now.

**Comment by hfiguiere** [comment] 2020-06-12 03:25
Not sure how this happened, but STK is broken. Will check again.

**Comment by hfiguiere** [comment] 2020-06-12 03:59
Reopened because I finally reproduced the STK problem and I have a fix. Sorry for taking so long but a one way bug report is always harder.

**Closed** 2020-06-12 04:33 UTC
